##
# Scheme On You
-
  name:  'Scheme On You - API Documents'
  uriPattern: 'openapi/document/{name}'
  defaults:
    '@package': 'Sitegeist.SchemeOnYou'
    '@controller': 'OpenApiDocument'
    '@action': 'render'
  httpMethods: ['GET']
