Neos:
  Flow:
    mvc:
      routes:
        Sitegeist.SchemeOnYou:
          position: "before Neos.Neos"

Sitegeist:
  SchemeOnYou:
    # The OpenApi root object, see https://swagger.io/specification/#openapi-object
    rootObject:
      openapi: '3.1.0'
      info: {}
      servers: {}
      paths: {}
      webhooks: {}
      components: {}
      security: {}
      tags: {}
      externalDocs: {}

    # the separate dictionaries that may be rendered
    # example: {name: string, classNames: [string]}
    documents: []


